#!/bin/bash
ls -1aF | LC_COLLATE=C sort -df | awk '{if ($0 == "." || $0 == "..") {print $0} else if (substr($0,1,1) == ".") {printf "%s,", $0} else if (substr($0,length($0),1) == "/") {printf "%s\n", $0} else {printf "%s,", $0}}'

